config/routes.rb
Rails.application.routes.draw do
  resources :users, :locations, :images, :tags
  root "locations#index"
end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :locations
  belongs_to :users
  has_and_belongs_to_many :tags

  def date
  	self.created_at.to_date.to_s(:long)
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :images

  geocoded_by :address, :latitude => :latitude, :longitude => :longitude
  #need to be tested
  reverse_geocoded_by :latitude, :longitude, :address => :address
  #explain geocoder!
  after_validation :geocode, :reverse_geocode
  #explain before destroy.
  before_destroy :delete_fusion_table


  # def has_address_or_coordinates
  #   if address.blank? && (latitude.blank? || longitude.blank?)
  #     errors.add(:address_of_coords, "Wifi Hotspots need an address or coordinates to validate.")
  #   end
  # end

  def nearby_location(dist)
    data = Location.all
    nearby_wifi = data.select { |spot| self.distance_to([spot.latitude,spot.longitude]) <= dist }
    sort_nearby_wifi = nearby_wifi.sort_by { |close| self.distance_to([close.latitude, close.longitude]) }
  end

  # def add_to_fusion_table
  #   table = FusionTableApi.get_fusion_table
  #   data = self.fusion_table_data
  #   table.insert data
  # end

  # def update_fusion_table
  #   table = FusionTableApi.get_fusion_table
  #   data = self.fusion_table_data
  #   row_id = table.select "ROWID", "WHERE OBJECTID=#{self.id.to_s}"
  #   table.delete "#{row_id[0][:rowid]}".to_i
  #   table.insert data
  # end
  #method for data

  # def fusion_table_data
  #   [{
  #     "OBJECTID" => self.id,
  #     "Boro"  => self.boro,
  #     "Location"  => self.place_name,
  #     "Latitude"  => self.latitude,
  #     "Longitude" => self.longitude
  #     }]
  # end

  # def delete_fusion_table
  #   table = FusionTableApi.get_fusion_table
  #   row_id = table.select "ROWID", "WHERE OBJECTID=#{self.id.to_s}"
  #   table.delete row_id[0][:rowid].to_i if row_id != []
  # end

  # def new_tweet
  #   client = TwitterApi.get_client
  #   client.update("New Wifi Hotspot at #{self.place_name}.")
  # end

  # def update_tweet
  #   client = TwitterApi.get_client
  #   client.update("Wifi Hotspot at #{self.place_name} has been edited.")
  # end

  # def add_fav_point
  #   self.fav_point == nil ? self.fav_point = 1 : self.fav_point += 1
  # end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  
  has_many_and_belongs_to :images


end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username

  has_many :images

  # def full_name
  # 	self.first_name + " " + self.last_name
  # end

  def sign_up_date
  	self.created_at.to_date.to_s(:long)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
    render :home
  end

  # def authenticate
  #   redirect_to login_path unless current_user
  # end

  # def current_user
  #   User.find(session[:current_user_id]) if session[:current_user_id]
  # end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def index
		@images = Image.all
	end

	def show
		@image = Image.find(params[:id])
	end

	def new
		@image = Image.new
	end

	def create

		@image = Image.new(image_params)
		@image.user_id = User.first.id
		@image.location_id = Location.find(1).id
		if @image.save
			flash[:success] = "Image Added!"
			redirect_to location_path(Location.find(1).id)
		else
			render :new
		end
	end

	def edit
		@image = Image.find(params[:id])
	end

	def update
		@image = Image.find(params[:id])
		if @image.update(image_params)
			redirect_to image_path(@image)
		else
			render :edit
		end
	end

	def destroy
		image = Image.find(params[:id])
		if image.destroy
			redirect_to images_path
		else
			redirect_to edit_image_path(image)
		end
	end

	private

	def image_params
		params.require(:image).permit(:location_id,:user_id,:img_url)
	end
end

app/controllers/locations_contoller.rb
class LocationsController < ApplicationController

	def index
		@locations = Location.all
	end

	def show
		@location = Location.find(params[:id])
	end

	def new
		@location = Location.new
	end

	def create
		@location = Location.new(location_params)
		if @location.save
			redirect_to location_path(@location)
		else
			render :new
		end
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		if @location.update(location_params)
			redirect_to location_path(@location)
		else
			render :edit
		end
	end

	def destroy
		location = Location.find(params[:id])
		if location.destroy
			redirect_to locations_path
		else
			redirect_to edit_location_path(location)
		end
	end

	private

	def location_params
		params.require(:location).permit(:name,:nationality,:genre,:photo_url)
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def index
		@locations = Location.all
	end

	def show
		@location = Location.find(params[:id])
	end

	def new
		@location = Location.new
	end

	def create
		@location = Location.new(location_params)
		if @location.save
			redirect_to location_path(@location)
		else
			render :new
		end
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		if @location.update(location_params)
			redirect_to location_path(@location)
		else
			render :edit
		end
	end

	def destroy
		location = Location.find(params[:id])
		if location.destroy
			redirect_to locations_path
		else
			redirect_to edit_location_path(location)
		end
	end

	private

	def location_params
		params.require(:location).permit(:name,:nationality,:genre,:photo_url)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		@tags = Tag.all
	end

	def show
		@tag = Tag.find(params[:id])
	end

	def new
		@tag = Tag.new
	end

	def create
		@tag = Tag.new(tag_params)
		if @tag.save
			redirect_to tag_path(@tag)
		else
			render :new
		end
	end

	def edit
		@tag = Tag.find(params[:id])
	end

	def update
		@tag = Tag.find(params[:id])
		if @tag.update(tag_params)
			redirect_to tag_path(@tag)
		else
			render :edit
		end
	end

	def destroy
		tag = Tag.find(params[:id])
		if tag.destroy
			redirect_to tags_path
		else
			redirect_to edit_tag_path(tag)
		end
	end

	private

	def tag_params
		params.require(:tag).permit(:name,:nationality,:genre,:photo_url)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to user_path(@user)
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path(@user)
		else
			render :edit
		end
	end

	def destroy
		user = User.find(params[:id])
		if user.destroy
			redirect_to users_path
		else
			redirect_to edit_user_path(user)
		end
	end

	private

	def user_params
		params.require(:user).permit(:name,:nationality,:genre,:photo_url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<iframe width="500" height="300" scrolling="no" frameborder="no" src="https://www.google.com/fusiontables/embedviz?q=select+col2+from+1pqCsRPJ_4K3b_RTyHKVJ_puFYbp1fMQ7wRu9Pzf6&amp;viz=MAP&amp;h=false&amp;lat=40.705738043378645&amp;lng=-73.92458209842528&amp;t=1&amp;z=16&amp;l=col2&amp;y=2&amp;tmplt=2&amp;hml=GEOCODABLE"></iframe>

<% @locations.each do |location| %> 
<%= link_to "#{location.address}", @location %>
<% end %>

app/views/images/_image_display.html.erb
<div class="image_box">
	<img src="<%= image.img_url %>">
	<p><%= @user.username%></p>
	<a href="/images/<%= image.id %>"><p>image page</p></a>
	<p><%= render "tags" %></p>
	<p class="image_stat"><%= image.created_at %><a href="/images/<%=image.id%>/edit">Edit</a></p>
</div>

app/views/images/_tags.html.erb
<% image.tags.each do |tag| %>
		<%= tag.name %>
<% end %>

app/views/images/new.html.erb
<%= form_for @image do |f| %>

	<%= f.label :img_url %>
  <%= f.text_field :img_url %>

	<%= f.hidden_field :user_id %>
  <%= f.hidden_field :location_id %>

 	<%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taggr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<ul>
		<li><a class="logo" href="<% locations_path %>"><img src="https://mail.google.com/mail/u/0/?ui=2&ik=43da42c106&view=fimg&th=14a2138877649aec&attid=0.1&disp=inline&realattid=f_i3df007n0&safe=1&attbid=ANGjdJ8go7TYR_Gk3C_4UBnJkakoV6E5EZwkPazvQKoSu7WibLYPyXfwr5GDJq7QXeoF3YvkEUOR12hq6Ncf3rWTHX240d5p7VFihiX-HMDV1cTFPCEr07QMSYQiuE8&ats=1417903542890&rm=14a2138877649aec&zw&sz=w1256-h642"></a></li>
		<li class="li"><%= link_to "near me", location_path(1) %></li>
		<li class="li"><%= link_to "about", locations_path%></li>
		<li class="li"><%= link_to "log in", locations_path %></li>
	</ul>
	</header>

<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
<iframe width="1000" height="800" scrolling="no" frameborder="no" src="https://www.google.com/fusiontables/embedviz?q=select+col2+from+1pqCsRPJ_4K3b_RTyHKVJ_puFYbp1fMQ7wRu9Pzf6&amp;viz=MAP&amp;h=false&amp;lat=40.705738043378645&amp;lng=-73.92458209842528&amp;t=1&amp;z=16&amp;l=col2&amp;y=2&amp;tmplt=2&amp;hml=GEOCODABLE"></iframe>

app/views/locations/show.html.erb
<div class="add_photo"><%= link_to "Add a photo to this site!", new_image_path %><br><%= flash[:success] %></div>

<% @location.images.order(created_at: :desc).each do |image| %>
	<img src=<%= "#{image.img_url}"  %>>
<% end %>

app/views/users/_form.html.erb
<% @user.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
<% end %>

<%= form_for @author do |f| %>
	<%= f.label :username %><br>
	<%= f.text_field :username %><br>

	<%= f.label :password %><br>
	<%= f.password_field :password %><br>

	<%= f.label :password_confirmation %><br>
	<%= f.password_field :password_confirmation %><br>

	<%= f.label :img_url %><br>
	<%= f.text_field :img_url %><br>

	<%= f.label :bio %><br>
	<%= f.text_field :bio %><br>

	<%= f.label :location %><br>
	<%= f.text_field :location %><br>

	<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<div class="large_post_box">
	<h3>Edit your Account</h3>
	<%= render "form" %>

	<form action="/users/<%= @user.id%>" method="post">
		<input type="hidden" name="_method" value="DELETE">
		<button>Remove</button>
	</form>
</div>

app/views/users/index.html.erb
<div id="columns">
	<% @users.each do |user| %>
		
		<div class="post_box user_bkgd">
			<p><%= user.username %></p>
			<a href="/users/<%= user.id %>"></a>
		<p class="post_stat"><%= user.bio %><br><%=user.location%> | 
			<% if user.id == session[:current_user_id] %>
				<a href="/authors/<%=author.id%>/edit">Edit</a></p>
			<% end %>
		</div>

	<% end %>
</div>

app/views/users/new.html.erb
<div class="large_post_box">
	<h3>Sign Up</h3>
	<%= render "form" %>
</div>

app/views/users/show.html.erb
<div class="user_header">
	<p><%= @user.username%></p>
	<p class="post_stat"> | <a href="/users/<%=@user.id%>/edit">Edit</a>
	</p>
</div>